 language: node_js
 node_js:
   - "0.8"
 script:
   - "npm test --coverage"
   - "node node_modules/.bin/istanbul check-coverage --functions 90 --statements 90 --branches 90 --lines 90"
 git:
   depth: 1

